# Site settings
title: Nicole Venus
email: nicole[dot]venus[at]usi[dot]ch
description: >
  PhD candidate in Economics <br/>
  Università della Svizzera italiana (USI) <br/>
  Via Giuseppe Buffi 13 <br/>
  CH-6900 Lugano TI, Switzerland <br/>
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nicolevenus.github.io/" # the base hostname & protocol for your site
twitter_username: #JAlexBranham
github_username:  nicolevenus
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
