# Site settings
title: Nicole Venus
description: > # this means to ignore newlines until "baseurl:"
  PhD candidate in Economics
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nicolevenus.github.io/" # the base hostname & protocol for your site
#theme: minima
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username:  nicolevenus

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
