# Site settings
author:
  name   : "Nicole Venus"
    #avatar : "/assets/images/bio-photo.jpg"
    bio    : "Developing software since 1980"
    links:
      - label: "Twitter"
        icon: "fab fa-fw fa-twitter-square"
        url: "https://twitter.com/"
       #or url: "https://twitter.com/BodoTe" ?
title: Nicole Venus
email: nicole[dot]venus[at]usi[dot]ch
description: > # this means to ignore newlines until "baseurl:"
  PhD candidate in Economics
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://nicolevenus.github.io/" # the base hostname & protocol for your site
theme: minima

github_username:  nicolevenus

permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
